-- =============================================
-- Author:		Oscar Valles
-- Create date: 5/19/2011
-- Description:	Obtain Annual Utilization based
--              on Prescription Date
--				Accept up to 20 NDCs
-- =============================================

CREATE PROCEDURE Annual_VDP_RxDt

-- Declare Varible for Date Range Values
		@BEGIN_DATE datetime, @END_DATE datetime,

-- Declare variables to hold NDC values.  There are 15 NDC variables declared
    	@NDC01 varchar(11), @NDC02 varchar(11), @NDC03 varchar(11), @NDC04 varchar(11), @NDC05 varchar(11), 
		@NDC06 varchar(11), @NDC07 varchar(11), @NDC08 varchar(11), @NDC09 varchar(11), @NDC10 varchar(11),
		@NDC11 varchar(11), @NDC12 varchar(11), @NDC13 varchar(11), @NDC14 varchar(11), @NDC15 varchar(11),
		@NDC16 varchar(11), @NDC17 varchar(11), @NDC18 varchar(11), @NDC19 varchar(11), @NDC20 varchar(11),

-- Declare variable to hold the max OAGID from Prims2
		@OAGID bigint

AS

IF @OAGID IS NULL

BEGIN

SELECT @OAGID = MAX([OAGID]) FROM [Prims2].[dbo].[FH_Vd_Claims];

-- BEGIN THE QUERY
SELECT
      PRODUCT_ID_NDC
      ,M.LABEL_NAME
      ,SUM(CASE WHEN CLM_STAT = 'RV' OR CLM_STAT = 'RH' 
				 THEN -1 ELSE 1 
			END) AS CLAIM_COUNT

      ,year(RX_DT) as CLAIM_YR
	  ,SUM(UC_SUBMIT_AMT) AS TOTAL_AMT_BILLED
      ,SUM(TOTAL_CLM_AMT_PD) AS TOTAL_CLM_AMT_PD
	  ,SUM(
		CASE
			WHEN CLM_STAT = 'RV' OR CLM_STAT = 'RH' THEN QTY_DISPENSED * -1 
			ELSE QTY_DISPENSED
		END) AS QTY_DISPENSED
	  ,SUM(
		CASE
			WHEN CLM_STAT = 'RV' OR CLM_STAT = 'RH' THEN DISP_EXP_AMT_PD * -1 
			ELSE DISP_EXP_AMT_PD
		END) AS DISP_EXP_AMT_PD
	  ,SUM(
		CASE
			WHEN CLM_STAT = 'RV' OR CLM_STAT = 'RH' THEN INGRED_COST_VDP_CALC * -1 
			ELSE INGRED_COST_VDP_CALC
		END) AS INGRED_COST_VDP_CALC
  INTO #tmpAnnualUtilization
  FROM [Prims].[dbo].[VDP_ECM_CLAIMS] C
LEFT JOIN [Prims2].[dbo].[FH_Mfads_ndc] M
ON M.NDC = C.PRODUCT_ID_NDC
WHERE [RX_DT] BETWEEN @BEGIN_DATE AND @END_DATE
AND  [PRODUCT_ID_NDC] IN (
@NDC01
,@NDC02
,@NDC03
,@NDC04
,@NDC05
,@NDC06
,@NDC07
,@NDC08
,@NDC09
,@NDC10
,@NDC11
,@NDC12
,@NDC13
,@NDC14
,@NDC15
,@NDC16
,@NDC17
,@NDC18
,@NDC19
,@NDC20
)
GROUP BY
      PRODUCT_ID_NDC
      ,M.LABEL_NAME
      ,YEAR(RX_DT)

UNION ALL

SELECT
      PRODUCT_ID_NDC
      ,M.LABEL_NAME
      ,SUM(CASE WHEN CLM_STAT = 'RV' OR CLM_STAT = 'RH' 
				 THEN -1 ELSE 1 
			END) AS CLAIM_COUNT
      ,year(RX_DT) as CLAIM_YR
	  ,SUM(UC_SUBMIT_AMT) AS TOTAL_AMT_BILLED
      ,SUM(TOTAL_CLM_AMT_PD) AS TOTAL_CLM_AMT_PD
	  ,SUM(
		CASE
			WHEN CLM_STAT = 'RV' OR CLM_STAT = 'RH' THEN QTY_DISPENSED * -1 
			ELSE QTY_DISPENSED
		END) AS QTY_DISPENSED
	  ,SUM(
		CASE
			WHEN CLM_STAT = 'RV' OR CLM_STAT = 'RH' THEN DISP_EXP_AMT_PD * -1 
			ELSE DISP_EXP_AMT_PD
		END) AS DISP_EXP_AMT_PD
	  ,SUM(
		CASE
			WHEN CLM_STAT = 'RV' OR CLM_STAT = 'RH' THEN INGRED_COST_VDP_CALC * -1 
			ELSE INGRED_COST_VDP_CALC
		END) AS INGRED_COST_VDP_CALC
  FROM [Prims2].[dbo].[FH_Vd_Claims] C
LEFT JOIN [Prims2].[dbo].[FH_Mfads_ndc] M
ON M.NDC = C.PRODUCT_ID_NDC
WHERE [RX_DT] BETWEEN @BEGIN_DATE AND @END_DATE
AND  [PRODUCT_ID_NDC] IN (
@NDC01
,@NDC02
,@NDC03
,@NDC04
,@NDC05
,@NDC06
,@NDC07
,@NDC08
,@NDC09
,@NDC10
,@NDC11
,@NDC12
,@NDC13
,@NDC14
,@NDC15
,@NDC16
,@NDC17
,@NDC18
,@NDC19
,@NDC20
)
GROUP BY
      PRODUCT_ID_NDC
      ,M.LABEL_NAME
      ,YEAR(RX_DT)
ORDER BY
year(RX_DT)
, PRODUCT_ID_NDC; 

SELECT [PRODUCT_ID_NDC]
,[LABEL_NAME]
,[CLAIM_YR] AS PRESCRIPTION_YEAR
,SUM([CLAIM_COUNT]) AS [CLAIM_COUNT]
,SUM([TOTAL_AMT_BILLED]) AS [TOTAL_AMT_BILLED]
,SUM([TOTAL_CLM_AMT_PD]) AS [TOTAL_CLM_AMT_PD]
,SUM([QTY_DISPENSED]) AS [QTY_DISPENSED]
,SUM([DISP_EXP_AMT_PD]) AS [DISP_EXP_AMT_PD]
,SUM([INGRED_COST_VDP_CALC]) AS [INGRED_COST_VDP_CALC]
,@OAGID AS MAX_OAGID
FROM #tmpAnnualUtilization
GROUP BY [PRODUCT_ID_NDC]
,[LABEL_NAME]
,[CLAIM_YR]
ORDER BY 3, 2;

DROP TABLE #tmpAnnualUtilization;
END

ELSE

-- THIS QUERY WILL EXECUTE IF AN OAGID VALUE IS PRESENTED

BEGIN

SELECT
      PRODUCT_ID_NDC
      ,M.LABEL_NAME
      ,SUM(CASE WHEN CLM_STAT = 'RV' OR CLM_STAT = 'RH' 
				 THEN -1 ELSE 1 
			END) AS CLAIM_COUNT

      ,YEAR(RX_DT) as CLAIM_YR
	  ,SUM(UC_SUBMIT_AMT) AS TOTAL_AMT_BILLED
      ,SUM(TOTAL_CLM_AMT_PD) AS TOTAL_CLM_AMT_PD
	  ,SUM(
		CASE
			WHEN CLM_STAT = 'RV' OR CLM_STAT = 'RH' THEN QTY_DISPENSED * -1 
			ELSE QTY_DISPENSED
		END) AS QTY_DISPENSED
	  ,SUM(
		CASE
			WHEN CLM_STAT = 'RV' OR CLM_STAT = 'RH' THEN DISP_EXP_AMT_PD * -1 
			ELSE DISP_EXP_AMT_PD
		END) AS DISP_EXP_AMT_PD
	  ,SUM(
		CASE
			WHEN CLM_STAT = 'RV' OR CLM_STAT = 'RH' THEN INGRED_COST_VDP_CALC * -1 
			ELSE INGRED_COST_VDP_CALC
		END) AS INGRED_COST_VDP_CALC
  INTO #tmpAnnualUtilwOAGID
  FROM [Prims].[dbo].[VDP_ECM_CLAIMS] C
LEFT JOIN [Prims2].[dbo].[FH_Mfads_ndc] M
ON M.NDC = C.PRODUCT_ID_NDC
WHERE [RX_DT] BETWEEN @BEGIN_DATE AND @END_DATE
AND  [PRODUCT_ID_NDC] IN (
@NDC01
,@NDC02
,@NDC03
,@NDC04
,@NDC05
,@NDC06
,@NDC07
,@NDC08
,@NDC09
,@NDC10
,@NDC11
,@NDC12
,@NDC13
,@NDC14
,@NDC15
,@NDC16
,@NDC17
,@NDC18
,@NDC19
,@NDC20
)
GROUP BY
      PRODUCT_ID_NDC
      ,M.LABEL_NAME
      ,YEAR(RX_DT)

UNION ALL

SELECT
      PRODUCT_ID_NDC
      ,M.LABEL_NAME
      ,SUM(CASE WHEN CLM_STAT = 'RV' OR CLM_STAT = 'RH' 
				 THEN -1 ELSE 1 
			END) AS CLAIM_COUNT
      ,YEAR(RX_DT) as CLAIM_YR
	  ,SUM(UC_SUBMIT_AMT) AS TOTAL_AMT_BILLED
      ,SUM(TOTAL_CLM_AMT_PD) AS TOTAL_CLM_AMT_PD
	  ,SUM(
		CASE
			WHEN CLM_STAT = 'RV' OR CLM_STAT = 'RH' THEN QTY_DISPENSED * -1 
			ELSE QTY_DISPENSED
		END) AS QTY_DISPENSED
	  ,SUM(
		CASE
			WHEN CLM_STAT = 'RV' OR CLM_STAT = 'RH' THEN DISP_EXP_AMT_PD * -1 
			ELSE DISP_EXP_AMT_PD
		END) AS DISP_EXP_AMT_PD
	  ,SUM(
		CASE
			WHEN CLM_STAT = 'RV' OR CLM_STAT = 'RH' THEN INGRED_COST_VDP_CALC * -1 
			ELSE INGRED_COST_VDP_CALC
		END) AS INGRED_COST_VDP_CALC
  FROM [Prims2].[dbo].[FH_Vd_Claims] C
LEFT JOIN [Prims2].[dbo].[FH_Mfads_ndc] M
ON M.NDC = C.PRODUCT_ID_NDC
WHERE [RX_DT] BETWEEN @BEGIN_DATE AND @END_DATE
AND  [OAGID] <=  @OAGID
AND  [PRODUCT_ID_NDC] IN (
@NDC01
,@NDC02
,@NDC03
,@NDC04
,@NDC05
,@NDC06
,@NDC07
,@NDC08
,@NDC09
,@NDC10
,@NDC11
,@NDC12
,@NDC13
,@NDC14
,@NDC15
,@NDC16
,@NDC17
,@NDC18
,@NDC19
,@NDC20
)
GROUP BY
      PRODUCT_ID_NDC
      ,M.LABEL_NAME
      ,YEAR(RX_DT)
ORDER BY
YEAR(RX_DT)
, PRODUCT_ID_NDC; 

SELECT [PRODUCT_ID_NDC]
,[LABEL_NAME]
,[CLAIM_YR] AS PRESCRIPTION_YEAR
,SUM([CLAIM_COUNT]) AS [CLAIM_COUNT]
,SUM([TOTAL_AMT_BILLED]) AS [TOTAL_AMT_BILLED]
,SUM([TOTAL_CLM_AMT_PD]) AS [TOTAL_CLM_AMT_PD]
,SUM([QTY_DISPENSED]) AS [QTY_DISPENSED]
,SUM([DISP_EXP_AMT_PD]) AS [DISP_EXP_AMT_PD]
,SUM([INGRED_COST_VDP_CALC]) AS [INGRED_COST_VDP_CALC]
,@OAGID AS MAX_OAG_ID
FROM #tmpAnnualUtilwOAGID
GROUP BY [PRODUCT_ID_NDC]
,[LABEL_NAME]
,[CLAIM_YR]
ORDER BY 3, 2;

DROP TABLE #tmpAnnualUtilwOAGID;

END

